// ui
export const AUTH_START_LOADING = "AUTH_START_LOADING";
export const AUTH_STOP_LOADING = "AUTH_STOP_LOADING";
export const USER_START_LOADING = "USER_START_LOADING";
export const USER_STOP_LOADING = "USER_STOP_LOADING";

// auth
export const STORE_USERS = "STORE_USERS";
export const STORE_USER = "STORE_USER";