// ui
export const AUTH_START_LOADING = "AUTH_START_LOADING";
export const AUTH_STOP_LOADING = "AUTH_STOP_LOADING";
export const USER_START_LOADING = "USER_START_LOADING";
export const USER_STOP_LOADING = "USER_STOP_LOADING";
export const UI_START_LOADING = "UI_START_LOADING";
export const UI_STOP_LOADING = "UI_STOP_LOADING";
export const PRODUCTS_START_LOADING = "PRODUCTS_START_LOADING";
export const PRODUCTS_STOP_LOADING = "PRODUCTS_STOP_LOADING";
export const CART_START_LOADING = "CART_START_LOADING";
export const CART_STOP_LOADING = "CART_STOP_LOADING";

// auth
export const STORE_USERS = "STORE_USERS";
export const STORE_USER = "STORE_USER";

// products
export const STORE_CATEGORIES = "STORE_CATEGORIES";
export const STORE_NEW_CATEGORY = "STORE_NEW_CATEGORY";
export const STORE_PRODUCTS = "STORE_PRODUCTS";
export const ADD_PRODUCT_IN_STORE = "ADD_PRODUCT_IN_STORE";

// cart
export const STORE_CART = "STORE_CART";
export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_ITEM_FROM_CART = "REMOVE_ITEM_FROM_CART";
export const SET_PRODUCT_QTY = "SET_PRODUCT_QTY";